### PR TITLE
Fixed the issue #1577 i18n Team Loadout UI

### LINKED ISSUE #1577: i18n Team Loadout UI
Most of the UI that needs translation tagging are marked with `TODO: Translation` in code.

### PR DESCRIPTION
**Pull request by macerator-yaro**
## Describe your changes
Replaced the raw-string sections with `t` function or `Trans` component, and wrote them into the corresponding files in `libs/gi/localization/assets/locales/en`.

Below are the changes:
marked with `TODO: Translation` and raw-string sections on the Teams, Weapons, and Characters pages

If this PR is successfully merged, please upload the translations into POEditor.

## Issue or discord link
fixed #1577

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [ ] I have commented my code in hard-to understand areas.
- [ ] I have made corresponding changes to README or wiki.
- [x] For front-end changes, I have updated the corresponding English translations.
- [x] I have run `yarn run mini-ci` locally to validate format and lint.
- [ ] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

### CODE REVIEW

File: libs/gi/page-team/src/CharacterDisplay/Tabs/TabTheorycraft/index.tsx [hunk 1]
```diff
@@ -399,9 +399,17 @@ export default function TabTheorycraft() {
                   ))
                   .flatMap((value, index, array) => {
                     if (index === array.length - 2)
-                      return [value, <span key="and">, and </span>]
+                      return [
```
Comment (frzyc) [inline libs/gi/page-team/src/CharacterDisplay/Tabs/TabTheorycraft/index.tsx:402]: I think this can be done with more native i18next approach: https://www.i18next.com/translation-function/formatting#list

**Review by frzyc — CHANGES_REQUESTED** [review]
Mostly LGTM, very consistent tagging for l10n. One minor change for list formatting.

File: libs/gi/localization/assets/locales/en/page_character.json [hunk 2]
```diff
@@ -8,6 +8,45 @@
     "theorycraft": "Theorycraft",
     "upopt": "Artifact Upgrader"
   },
+  "buildCardTip": {
```
Comment (frzyc) [inline libs/gi/localization/assets/locales/en/page_character.json:11]: Not really an action to change, just more of an observation:
originally the bulk of character related content was on the character page, hence `page_character`, now, most of that is happening in the team page, hence `page_team`. However, things like builds and loadouts are actually shared between the two pages, since the character page has become a loadout/team manager. I am inclined to keep associated l10n in the same json, rather than splitting them by page, so I wonder if it makes sense to create separate l10n namespaces, such as `build.json` and `loadout.json` for l10ns specific to those concepts.

File: libs/gi/page-team/src/CharacterDisplay/Tabs/TabTheorycraft/index.tsx (hunk 1 above)
Comment (macerator-yaro) [reply libs/gi/page-team/src/CharacterDisplay/Tabs/TabTheorycraft/index.tsx:402]: I couldn’t figure out how to directly pass a JSX element to the t function.😢
It seems that only string array can be passed to the List format. When I passed a JSX element array, it was displayed as [object Object].

Comment (macerator-yaro) [reply libs/gi/page-team/src/CharacterDisplay/Tabs/TabTheorycraft/index.tsx:402]: This was the only way I could think of lol
image

Comment (frzyc) [reply libs/gi/page-team/src/CharacterDisplay/Tabs/TabTheorycraft/index.tsx:402]: I see, you add a token to the Intl.ListFormat, generate, and then replace the tokens. I think that is a fine solution for now. I am fine with this solution, I'd say you should try to use a less-used unicode character as the token. (maybe the newline character? since this is suppose to be a single line)

Comment (macerator-yaro) [reply libs/gi/page-team/src/CharacterDisplay/Tabs/TabTheorycraft/index.tsx:402]: Is this okay? Sorry if I misunderstood your intention.
image

Comment (macerator-yaro) [reply libs/gi/page-team/src/CharacterDisplay/Tabs/TabTheorycraft/index.tsx:402]: Sorry, you mean U+200B or something like that, right?
I tried that, but for some reason I got an 'Uncaught' error and it didn't work.

File: libs/gi/localization/assets/locales/en/page_character.json (hunk 2 above)
Comment (frzyc) [reply libs/gi/localization/assets/locales/en/page_character.json:11]: @macerator-yaro I discussed with Tech Lead, I think it would make sense to divide up the l10n into separate files. Can you move the build related terms to `build.json`, and loadout related terms to `loadout.json`?

File: libs/gi/page-team/src/CharacterDisplay/Tabs/TabTheorycraft/index.tsx (hunk 1 above)
Comment (frzyc) [reply libs/gi/page-team/src/CharacterDisplay/Tabs/TabTheorycraft/index.tsx]: cool, a very novel solution, nice thinking.

Comment (macerator-yaro) [reply libs/gi/page-team/src/CharacterDisplay/Tabs/TabTheorycraft/index.tsx]: Sorry again and again, I found the cause of the error. I hadn't taken locale differences into account at all.😭
I pushed the wrong fix, I will fix it, and move to the new namespace again tomorrow.

Comment (frzyc) [reply libs/gi/page-team/src/CharacterDisplay/Tabs/TabTheorycraft/index.tsx]: I'll change the PR to a draft for now, you can change it back to ready once you finish cooking

**Comment by macerator-yaro** [comment]
Terms have been moved to new namespaces. I'm not sure if this is the right way to divide it, but I gave it a try anyway.
and also List Formatting re-fix is finished.

File: libs/gi/localization/assets/locales/en/artifact.json [hunk 3]
```diff
@@ -121,5 +121,11 @@
   "rvSliderBtn": {
     "maximum": "MRV",
     "current": "RV"
+  },
+  "optExcludeModal": {
```
Comment (frzyc) [inline libs/gi/localization/assets/locales/en/artifact.json:125]: This is a optimizer config, should go to `page_character_optimizer.json`

File: libs/gi/localization/assets/locales/en/page_character_optimize.json [hunk 4]
```diff
@@ -115,9 +134,39 @@
     "cancel": "Cancel",
     "generateBuilds": "Generate Builds"
   },
+  "buildShowingNum": "Showing <2>{{count}}</2> build generated for <6/>.",
+  "generatedOn": "Build generated on: ",
+  "selectChar": "Select a character to generate builds.",
+  "clearBuildsBtn": "Clear Builds",
+  "createBuildTc": {
```
Comment (frzyc) [inline libs/gi/localization/assets/locales/en/page_character_optimize.json:141]: "createBuildTc", "createBuildReal" and "buildDisplay"  should go to `build.json`

**Review by frzyc — CHANGES_REQUESTED** [review]
Last bit of namespacing change, I appreciate all the work so far.

File: libs/gi/localization/assets/locales/en/page_character_optimize.json (hunk 4 above)
Comment (macerator-yaro) [reply libs/gi/localization/assets/locales/en/page_character_optimize.json]: Completed. :)

**Review by frzyc — APPROVED** [review]
LGTM, thanks for all your work!
