### PR TITLE
Fix misc. sheet bugs

### LINKED ISSUE #522: Slingshot passive should not work on Childe's stance change
image
image

### LINKED ISSUE #863: Remove unnecessary conditionals
Includes:
* Luxurious Sea-Lord dmg conditional
* Xingqiu damage reduction from skill
* Geo traveler energy restoration
* Isshin dmg
* Aquila passive
* Sayu A1
* Thoma C4

### LINKED ISSUE #915: Xiangling C4 is not increasing Pyronado's duration
image
image

### LINKED ISSUE #919: Standardize reaction multipliers to be percentages
image-1

### LINKED ISSUE #934: Dori C6 label error
image

### PR DESCRIPTION
**Pull request by nguyentvan7**
* Resolve #934 
* Resolve #915 
* Resolve #919 
* Resolve #863 
* Resolve #522

### CODE REVIEW

File: apps/frontend/src/app/Data/Weapons/Bow/Slingshot/index.tsx [hunk 1]
```diff
@@ -16,40 +17,34 @@ const [, trm] = trans("weapon", key)
...
-      on: {
-        fields: [{
-          node: normal_dmg_inc
-        }, {
-          node: charged_dmg_inc
-        }]
-      }
-    }
+    states: objectKeyMap(condPassiveStates, state => ({
+      name: trm(`${state}`),
```
Comment (frzyc) [inline apps/frontend/src/app/Data/Weapons/Bow/Slingshot/index.tsx:41]: `trm(state)`

**Comment by frzyc** [comment]
other than slight nit, lgtm
