### PR TITLE
Bugfixes for comparisons when editing an inactive build and team multi-select

### LINKED ISSUE #2466: Equip confirmation displays the wrong comparison when modifying an inactive build
The comparisons displayed in the equipment swap confirmation are always for the currently active build, which results in the wrong comparisons being displayed when modifying an inactive build. Only the comparison is incorrect; equipment changes are made to the correct build.

https://github.com/user-attachments/assets/122efac2-abeb-4814-be8a-04c39452c525

### PR DESCRIPTION
**Pull request by arquelion**
## Describe your changes
**Fix for incorrect comparisons being displayed when trying to edit a build other than the current active build**
New file `BuildEditContext.tsx`:
- In order to display the correct comparisons for inactive builds, information regarding which build is currently being edited needs to be piped through to `CompareBuildWrapper` instead of always fetching `LoadoutDatum.buildId`, which always corresponds to the active build if the active build isn't the equipped build. `BuildEditContext` contains a single string set to either `"equipped"` (if the equipped build is being edited) or `LoadoutDatum.buildId` (if a non-equipped build is being edited). `CompareBuildWrapper` will then use this to fetch the weapon/artifact ids accordingly. This avoids needing to manually pipe this value through all the components on the build edit path.
- Export added to `gi/ui/src/context/index.ts`

`TeamDataManager.ts`:
- Added new methods `getEditWeaponId`/`getEditArtifactIds` - These determine the type of build being edited then pass that along with `teamCharId` and the `buildId` to the new private methods below to actually fetch the ids needed for comparison. Build types are deduced to always be either `'equipped'` or `'real'` as it makes no sense to edit a TC build in this context.
- Added private methods `getWeaponId` and `getArtifactIds` - These contain the code previously in `getLoadoutWeaponId` and `getLoadoutArtifactIds` to reduce code duplication.
- Modified `getLoadoutWeaponId`/`getLoadoutArtifactIds` to use the private methods above (functionality unchanged)

`BuildReal.tsx`, `EquipmentSection.tsx`, `character/editor/Content.tsx`:
All three of these locations now wrap their `EquippedGrid` component with `BuildEditContext.Provider` and provide either `buildId` or `"equipped"` as the value.

**Bonus bugfix: Teammate multi-select drops a character if that character was moved to a different slot from the first slot and the team is not full**
`TeamSetting/index.tsx`:
Changed the last conditional in `onSelect` to use `database.teams.get(teamId)` instead of `team` from earlier in the function - This ensures that changes applied so far to the team are accounted for when checking whether a character has been displaced from their old slot regardless of which slot it was, preventing conditional from being false in cases where a character has been moved but `loadoutData[selectedIndex]` is undefined.

## Issue or discord link
- Fixes #2466 
- Fixes this bonus bug discovered while testing the comparison fix

https://github.com/user-attachments/assets/9012aeb2-a5c8-44da-ba56-40d97da91dc1

## Testing/validation
Build edit comparison fix:

https://github.com/user-attachments/assets/7a226a74-74db-4922-a0cd-726e190da4b9

https://github.com/user-attachments/assets/8bb382c1-d58a-4636-8930-0f5e5535f7fa

https://github.com/user-attachments/assets/3f69ba11-673a-454f-b976-16609cf6d64a

Team multi-select fix:

https://github.com/user-attachments/assets/19016ac0-9be2-4645-842d-c830e973b095

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [x] I have commented my code in hard-to understand areas.
- [x] I have made corresponding changes to README or wiki.
- [x] For front-end changes, I have updated the corresponding English translations.
- [x] I have run `yarn run mini-ci` locally to validate format and lint.
- [x] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

### CODE REVIEW

File: libs/gi/ui/src/context/BuildEditContext.tsx [hunk 1]
```diff
@@ -0,0 +1,12 @@
+'use client'
+import { createContext } from 'react'
+
+export type BuildEditContextObj = {
+  buildToEdit: string
```
Comment (frzyc) [inline libs/gi/ui/src/context/BuildEditContext.tsx:5]:
```suggestion
  buildToEdit: string | "equipped"
```

File: libs/gi/ui/src/context/BuildEditContext.tsx [hunk 2]
```diff
@@ -0,0 +1,12 @@
...
+  //setBuildIdToEdit: (buildId: string) => void
+}
+
+export const BuildEditContext = createContext({
```
Comment (frzyc) [inline libs/gi/ui/src/context/BuildEditContext.tsx:9]: could simplify this from an obj to an string, and maybe make "equipped" as default?
```suggestion
export const BuildEditContext = createContext<string | "equipped">("equipped")
```

File: libs/gi/ui/src/components/build/CompareBuildWrapper.tsx [hunk 3]
```diff
@@ -25,24 +26,30 @@ export function CompareBuildWrapper(props: WrapperProps) {
...
+    buildToEdit,
+    teamCharId
+  )
   const newWeaponId = weaponId ?? currentWeaponId
   return (
     <EquipBuildModal
       currentName={
-        (loadoutDatum.buildType === 'real' &&
-          database.builds.get(loadoutDatum.buildId)?.name) ||
+        (buildToEdit !== '' && database.builds.get(buildToEdit)?.name) ||
```
Comment (frzyc) [inline libs/gi/ui/src/components/build/CompareBuildWrapper.tsx:52]:
```suggestion
        database.builds.get(buildToEdit)?.name ?? "Equipped"
```

File: libs/gi/page-team/src/CharacterDisplay/Build/BuildReal.tsx [hunk 4]
```diff
@@ -212,7 +230,7 @@ function BuildEditor({
     const { name, description } = newBuild
     setName(name)
     setDesc(description)
-  }, [database, buildId])
+  }, [database, buildId, teamId, teamCharId])
```
Comment (frzyc) [inline libs/gi/page-team/src/CharacterDisplay/Build/BuildReal.tsx:233]: I am not sure if adding these to the dependency is necessary, can you explain?

**Review by frzyc — CHANGES_REQUESTED** [review]
Looks mostly good to me. thanks for resolving this difficult issue. I have some minor comments that warrants addressing.

File: libs/gi/page-team/src/CharacterDisplay/Build/BuildReal.tsx (hunk 4 above)
Comment (arquelion) [reply libs/gi/page-team/src/CharacterDisplay/Build/BuildReal.tsx:233]: Oh woops, those aren't supposed to be there anymore. Must've snuck back while I was solving the merge conflicts during rebase

File: libs/gi/ui/src/context/BuildEditContext.tsx (hunk 1 above)
Comment (arquelion) [reply libs/gi/ui/src/context/BuildEditContext.tsx]: done

File: libs/gi/ui/src/context/BuildEditContext.tsx (hunk 2 above)
Comment (arquelion) [reply libs/gi/ui/src/context/BuildEditContext.tsx]: done

File: libs/gi/ui/src/components/build/CompareBuildWrapper.tsx (hunk 3 above)
Comment (arquelion) [reply libs/gi/ui/src/components/build/CompareBuildWrapper.tsx]: done

**Review by frzyc — APPROVED** [review]
LGTM, thanks for your work!
