### PR TITLE
Fix misc. sheet issues, mess with individual character page structure, conditionals, etc.

### LINKED ISSUE #1078: Add "Burst Active" toggle for Raiden's elemental skill.
Raiden's E is affected by her C2, but only while the burst is active, if the burst is not active then her E does not gain DEF ignore.

### LINKED ISSUE #1193: Kirara's C2 Shields are possibly being miscalculated
image
This is the current formula for her C2 Shield DMG Absorption. 
I believe this may be mistaken, as the Constellation states the shields possess 40% of her Skill's `Max Shield DMG Absorption`.
However, the 40% Multiplier is only being applied on `20% Max HP`, and not on the full Max Shield DMG Absorption of `20% Max HP + 2042` (at Talent Level 4).

### PR DESCRIPTION
**Pull request by PolomoPT**
I'll update this description soon. Will list everything I messed with that wasn't just visual (read: stuff that would be bad if messed up/that people need to know about)

Sorry Van. pls ask me about anything
😭 

Changes:
Any changes that are not simply aesthetic or have any relevance to people besides me and Van have the word "important" and/or are in bold

Aloy: The changes here are actually all aesthetic. I reformatted the Coil conditional but I think there are no implications whatsoever.

Amber: Added C4 "additional charges" header

Arataki Itto: Changes an st to stg ig

Baizhu: Added C1 Additional charges header

Beidou: +- important So C6 had to have a conditional for applying the Electro RES Shred. And the Burst had DMG Reduction in there, y'see, being applied regardless of whether it was on. So I made a conditional that appears regardless of constellation and applies the DMG Reduction, while additionally giving the Electro RES when at C6.

Bennett: Only aesthetic changes. Removed useless nodes/text being displayed when they shouldn't.

Candace: st -> chg

Chongyun: Made A1 ATK SPD have a Header

Collei: **IMPORTANT: added a conditional for C2 Energy Recharge.** Moved A1 to a Header within Skill

Cyno: **+- important: C1 used to display unconditionally, but that's no good. Since ATK SPD effect isn't used by optimizer, i just wiped it.** Other than that, moves headers a little and adds a few text nodes to the burst conditional, changes a few strings to chg.

Dehya: I wanted to use my fancy new stg and st so I changed text and added energy regen node to c4

Diluc: Changed his c2 cond from take dmg to get hit because that's how it works according to kqm tcl

Diona: Added nodes for c2 shields, header in c2, c2 effects as header in Skill.

Eula: Changed some node display order to match in-game. Changed ch to st.

Faruzan: **IMPORTANT: Added conditional for c6 because it doesn't snapshot while the regular buffs from Benefit do**

Fischl: **IMPORTANT: Changes C4 and C1 dmg nodes to be listed under the respective constellations (this WILL BREAK multi-opts!!). Adds headers for constellation effects.**

Ganyu: Added Additional charges header from 2

Hu Tao: Moved "CD" out of conditional. Change Activation Cost to st so it can be translated. Added Blood Blossom duration. Added incInterRes to C6.

Jean: syntax

Kazuha: syntax, moved A1 as header to Skill. Used new "effect duration" st's for his a4

Kaeya: Changed text display logic for c2 burst duration

Ayato: Moved Shunsuiken DMG out of conditional (conditional deleted). had to adjust a lot of canShows accordingly.

Keqing: moved c1 dmg as header to skill

Kirara: moved c2 shields into c2. (Did not fix https://github.com/frzyc/genshin-optimizer/issues/1193 yet, because I'm not sure if it's indeed an issue)

Klee: added "Charges | 2" to her Skill

Kujou Sara: her skill cond had a useless node (showing the ratio of increase). Changed a little logic of her skill conditional, but it shouldn't have any effects. Moved c6 and a4 effects to headers under Skill.

Kuki: Changed ch to st. Will be able to transfer translation, btw.

Layla: moved c1 shields to c1

Mika: fixed Soulwind duration percentage thing from bug reports

Mona: changed CritRateIncNeg to CritRateInc because math.abs already converts it to positive. Removed c4 conditional, moved the effects to burst. did a ch -> chg. Added duration to c1. Changed c6 unit to seconds.

Nahida: st -> stg. turned c4 into a team buff because it's EM. I dunno if I should've.

Nilou: Changed all references of "Watery Moon" to "Luminous Illusion" (will no longer break multi-opts). Added effect duration [element] to her c2 effects because i can.

Ningguang: added headers to passive and conditionals ability

Noelle: added headers. the way i did it for c6 attack increase meant i made a new node, alright?

Qiqi: **+- important: Turned A1 Healing Bonus into buff to active char**

Raiden: **Important: added conditional to her Burst that does... nothing, pre-C2, so I filled it with text nodes. post-c2, it fixes #1078** 

Razor: Changed text used by his wolf attacks so it makes sense. Added a few text nodes to his burst conditional.

Kokomi: moved her burst healing nodes out of conditional. Moved c4 and c6 effects and cond to Burst.

Sayu: **Changes:
Any changes that are not simply aesthetic or have any relevance to people besides me and Van have the word "important" and/or are in bold

Aloy: The changes here are actually all aesthetic. I reformatted the Coil conditional but I think there are no implications whatsoever.

Amber: Added C4 "additional charges" header

Arataki Itto: Changes an st to stg ig

Baizhu: Added C1 Additional charges header

Beidou: +- important So C6 had to have a conditional for applying the Electro RES Shred. And the Burst had DMG Reduction in there, y'see, being applied regardless of whether it was on. So I made a conditional that appears regardless of constellation and applies the DMG Reduction, while additionally giving the Electro RES when at C6.

Bennett: Only aesthetic changes. Removed useless nodes/text being displayed when they shouldn't.

Candace: st -> chg

Chongyun: Made A1 ATK SPD have a Header

Collei: IMPORTANT: added a conditional for C2 Energy Recharge. Moved A1 to a Header within Skill

Cyno: +- important: C1 used to display unconditionally, but that's no good. Since ATK SPD effect isn't used by optimizer, i just wiped it. Other than that, moves headers a little and adds a few text nodes to the burst conditional, changes a few strings to chg.

Dehya: I wanted to use my fancy new stg and st so I changed text and added energy regen node to c4

Diluc: Changed his c2 cond from take dmg to get hit because that's how it works according to kqm tcl

Diona: Added nodes for c2 shields, header in c2, c2 effects as header in Skill.

Eula: Changed some node display order to match in-game. Changed ch to st.

Faruzan: IMPORTANT: Added conditional for c6 because it doesn't snapshot while the regular buffs from Benefit do

Fischl: IMPORTANT: Changes C4 and C1 dmg nodes to be listed under the respective constellations (this WILL BREAK multi-opts!!). Adds headers for constellation effects.

Ganyu: Added Additional charges header from 2

Hu Tao: Moved "CD" out of conditional. Change Activation Cost to st so it can be translated. Added Blood Blossom duration. Added incInterRes to C6.

Jean: syntax

Kazuha: syntax, moved A1 as header to Skill. Used new "effect duration" st's for his a4

Kaeya: Changed text display logic for c2 burst duration

Ayato: Moved Shunsuiken DMG out of conditional (conditional deleted). had to adjust a lot of canShows accordingly.

Keqing: moved c1 dmg as header to skill

Kirara: moved c2 shields into c2. Fix #1193 

Klee: added "Charges | 2" to her Skill

Kujou Sara: her skill cond had a useless node (showing the ratio of increase). Changed a little logic of her skill conditional, but it shouldn't have any effects. Moved c6 and a4 effects to headers under Skill.

Kuki: Changed ch to st. Will be able to transfer translation, btw.

Layla: moved c1 shields to c1

Mika: **+ - important: added conditional to c6 effect as it may not be active even when Soulwind is.** fixed Soulwind duration percentage thing from bug reports.

Mona: changed CritRateIncNeg to CritRateInc because math.abs already converts it to positive. Removed c4 conditional, moved the effects to burst. did a ch -> chg. Added duration to c1. Changed c6 unit to seconds.

Nahida: st -> stg. turned c4 into a team buff because it's EM. I dunno if I should've.

Nilou: Changed all references of "Watery Moon" to "Luminous Illusion" (will no longer break multi-opts). Added effect duration [element] to her c2 effects because i can.

Ningguang: added headers to passive and conditionals ability

Noelle: added headers. the way i did it for c6 attack increase meant i made a new node, alright?

Qiqi: +- important: Turned A1 Healing Bonus into buff to active char

Raiden: Important: added conditional to her Burst that does... nothing, pre-C2, so I filled it with text nodes. post-c2, it fixes https://github.com/frzyc/genshin-optimizer/issues/1078

Razor: Changed text used by his wolf attacks so it makes sense. Added a few text nodes to his burst conditional.

Kokomi: moved her burst healing nodes out of conditional. Moved c4 and c6 effects and cond to Burst.

Sayu: **IMPORTANT: Her Press Kick DMG formula was benefitting from her C2 "time spent in windwheel" buff, while Kick DMG does not spend any time in windwheel. this should be wrong, so i removed that**. Otherwise, ch -> stg, removed a weird header.

Shenhe: Idk why her A4 nodes had greaterEqs set to A1, so I changed that. Made her C4 display in Stacks unit. Moved C1 extra charge to C1.

Heizou: ch, stg -> chg. Added a canShow parameter to his c6 so it doesn't display a 0% value.

Sucrose: effect duration [element], additional charges added to c1.

Thoma: st -> stg

Tighnari: Added a duration parameter to.. his a1, i think?

Anemo Traveler: I didn't know why it had separate burst displays for main and party; deleted. Added a few "duration"s

Dendro Traveler: stg -> chg ig

Electro Traveler: **+- important: i'm pretty sure their c4 effects weren't being accounted for so i added a few nodes for the different values.**

Geo Traveler: stg -> chg; ch -> st

Venti: his c2 additional shots used to be displaying prior to c2. they no longer do. added header too. st -> stg

Wanderer: moved his c6 to NAs

Xiangling: Moved A4 up to Skill. deleted c6 duration because it was wrong (used c1 duration)

Xiao: **IMPORTANT: Added conditional to c2 energy recharge.** Changed a bit of his Burst stuffs to show either in- or outside of the conditional. according to what was needed. Also did additional charges under c1.

Xingqiu: moved burst dmg nodes outside the conditional

Xinyan: Removed Shield Level conditional (moved nodes outside it)

Yae Miko: Added a few stuff from skillParams that wasn't there (i couldn't find out what some were. if someone knows, help). Added text header listings for the effects of c1, c2 and c6. c2 and c6 are under Skill. Moved c4 conditional to under Skill. Added Charges number.

Yanfei: I guess I mvoed a few headers/effects (passive, constellations) to their respective passives and constellations. I think I also added some headers when needed.

Yaoyao: new strings yay

Yelan: additional charges and added 's' unit to c6 duration.

Yoimiya: moved c6 to under NAs, adjusted some node order to match in-game.

Yun Jin: added headers to c2 and c6 effects

Zhongli: Moved A1 to under Skill. st -> stg.

Weapons:

Royal Series: changed strings

Calamity Queller: **IMPORTANT: Added "off-field" conditional and expected effects (more atk from passive)**. Changed conditional name to the effect name, Consummation.

Deathmatch: changed from string to math lango

Other index.tsx files:

Fixed whitespace in many, also updated Scanner files.

Added a few html tags for colored text. messed with Elemental Resonance conditionals to add said colored text.

Strings:

Added some stgs. Cleaned up some sts, while adding some sts too. Reworded a ton of stuff to be cleaner, and deleted anything unused. Some common strings were turned from chs to sts, don't fret as their translation can be salvaged.

Made some grammar tweaks to text throughout the website.** Otherwise, ch -> stg, removed a weird header.

Shenhe: Idk why her A4 nodes had greaterEqs set to A1, so I changed that. Made her C4 display in Stacks unit. Moved C1 extra charge to C1.

Heizou: ch, stg -> chg. Added a canShow parameter to his c6 so it doesn't display a 0% value.

Sucrose: effect duration [element], additional charges added to c1.

Thoma: st -> stg

Tighnari: Added a duration parameter to.. his a1, i think?

Anemo Traveler: I didn't know why it had separate burst displays for main and party; deleted. Added a few "duration"s

Dendro Traveler: stg -> chg ig

Electro Traveler: +- important: i'm pretty sure their c4 effects weren't being accounted for so i added a few nodes for the different values.

Geo Traveler: stg -> chg; ch -> st

Venti: his c2 additional shots used to be displaying prior to c2. they no longer do. added header too. st -> stg

Wanderer: moved his c6 to NAs

Xiangling: Moved A4 up to Skill. deleted c6 duration because it was wrong (used c1 duration)

Xiao: IMPORTANT: Added conditional to c2 energy recharge. Changed a bit of his Burst stuffs to show either in- or outside of the conditional. according to what was needed. Also did additional charges under c1.

Xingqiu: moved burst dmg nodes outside the conditional

Xinyan: Removed Shield Level conditional (moved nodes outside it)

Yae Miko: Added a few stuff from skillParams that wasn't there (i couldn't find out what some were. if someone knows, help). Added text header listings for the effects of c1, c2 and c6. c2 and c6 are under Skill. Moved c4 conditional to under Skill. Added Charges number.

Yanfei: I guess I mvoed a few headers/effects (passive, constellations) to their respective passives and constellations. I think I also added some headers when needed.

Yaoyao: new strings yay

Yelan: additional charges and added 's' unit to c6 duration.

Yoimiya: moved c6 to under NAs, adjusted some node order to match in-game.

Yun Jin: added headers to c2 and c6 effects

Zhongli: Moved A1 to under Skill. st -> stg.

Weapons:

Royal Series: changed strings

Calamity Queller: IMPORTANT: Added "off-field" conditional and expected effects (more atk from passive)

Deathmatch: changed from string to math lango

Other index.tsx files:

Fixed whitespace in many, also updated Scanner files.

Added a few html tags for colored text. messed with Elemental Resonance conditionals to add said colored text.

Strings:

Added some stgs. Cleaned up some sts, while adding some sts too. Reworded a ton of stuff to be cleaner, and deleted anything unused. Some common strings were turned from chs to sts, don't fret as their translation can be salvaged.

Made some grammar tweaks to text throughout the website.

### CODE REVIEW

**Comment by nguyentvan7** [comment]
Next time, you should make lots of small PRs rather than one mega PR. it makes it much easier to review and adjust

**Comment by PolomoPT** [comment]
Changes:
_This will be a list of changes that were not simply aesthetic (strings or Header positions). Changes that have greater implications will also be highlighted_

Aloy: The changes here are actually all aesthetic. I reformatted the Coil conditional but I think there are no implications whatsoever.

Amber: **Added** C4 "additional charges" header

Arataki Itto: Changes an st to stg ig

Baizhu: **Added** C1 Additional charges header

Beidou: **Logic change:** So C6 had to have a conditional for applying the Electro RES Shred. And the Burst had DMG Reduction in there, y'see, being applied regardless of whether it was on. So I made a conditional that appears regardless of constellation and applies the DMG Reduction, while additionally giving the Electro RES when at C6.

Bennett: Only aesthetic changes. Removed useless nodes/text being displayed when they shouldn't.

Candace: st -> chg

Chongyun: Made A1 ATK SPD have a Header

Collei: `**Logic change:**` added a conditional for C2  Energy Recharge. Moved A1 to a Header within Skill

Cyno: **Kinda logic change:** C1 used to display unconditionally, but that's no good. Since ATK SPD effect isn't used by optimizer, i just wiped it. Other than that, moves headers a little and adds a **few text nodes to the burst conditional**, changes a few strings to chg.

Dehya: I wanted to use my fancy new stg and st so I changed text and **added energy regen node to c4**

Diluc: Changed his c2 cond from take dmg to get hit because that's how it works according to kqm tcl

Diona: **Added nodes for c2 shields**, header in c2, c2 effects as header in Skill.

Eula: Changed some node display order to match in-game. Changed ch to st.

Fischl: **IMPORTANT: Changes C4 and C1 dmg nodes to be listed under the respective constellations (this WILL BREAK multi-opts!!)**. Adds headers for constellation effects.

Ganyu: **Added** Additional charges header from 2

Hu Tao: Moved "CD" out of conditional. Change Activation Cost to st so it can be translated. Added Blood Blossom duration. Added incInterRes to C6.

Jean: syntax

Kazuha: syntax, moved A1 as header to Skill. Used new "effect duration" st's for his a4

Kaeya: Changed text display logic for c2 burst duration

Ayato: **Moved Shunsuiken DMG out of conditional (conditional deleted)**.  had to adjust a lot of canShows accordingly.

Keqing: moved  c1 dmg as header to skill

Kirara: moved c2 shields into c2. (Did not fix #1193 yet, because I'm not sure if it's indeed an issue)

Klee: added "Charges | 2" to her Skill

Kujou Sara: her skill cond had a useless node (showing the ratio of increase). Changed a little logic of her skill conditional, but it shouldn't have any effects. Moved c6 and a4 effects to headers under Skill.

Kuki: Changed ch to st. Will be able to transfer translation, btw.

Layla: moved c1 shields to c1

Mika: fixed Soulwind duration percentage thing from bug reports

Mona: changed CritRateIncNeg to CritRateInc because math.abs already converts it to positive. Removed c4 conditional, moved the effects to burst. did a ch -> chg. Added duration to c1. Changed c6 unit to seconds.

Nahida: st -> stg. **turned c4 into a team buff because it's EM. I dunno if I should've.**

Nilou: **IMPORTANT: Changed all references to "Watery Moon" to "Luminous Illusion". This breaks multi-opts and may affect databases, idk?** Added effect duration [element] to her c2 effects because i can.

Ningguang: added headers

Noelle: added headers. the way i did it for c6 attack increase meant i made a new node.

Qiqi: **+- important: Turned A1 Healing Bonus into team buff**

Raiden: **Important: added conditional to her Burst that does... nothing, pre-C2, so I filled it with text nodes. post-c2, it fixes #1078**

Razor: Changed text used by his wolf attacks so it makes sense. Added a few text nodes to his burst conditional.

**Comment by PolomoPT** [comment]
In retrospect, I guess this does _not_ fix #1078. There's still the edge-case of weapon passive damage. but it's still pretty good

File: apps/frontend/src/app/Data/Characters/Nahida/index.tsx [hunk 1]
```diff
@@ -523,6 +523,7 @@ const sheet: ICharacterSheet = {
         teamBuff: true,
         path: condC2QSAPath,
         value: condC2QSA,
+        canShow: equal(condC2Bloom, 'on', 1),
```
Comment (nguyentvan7) [inline apps/frontend/src/app/Data/Characters/Nahida/index.tsx:526]: Technically these are not linked, since the quicken, etal buff has an 8s duration

File: apps/frontend/src/app/Data/Characters/Nilou/index.tsx [hunk 2]
```diff
@@ -198,8 +198,8 @@ export const dmgFormulas = {
     dance2Dmg: dmgNode('hp', dm.skill.dance2Dmg, 'skill'),
     whirl1Dmg: dmgNode('hp', dm.skill.whirl1Dmg, 'skill'),
     whirl2Dmg: dmgNode('hp', dm.skill.whirl2Dmg, 'skill'),
-    moonDmg: dmgNode('hp', dm.skill.moonDmg, 'skill', {
-      premod: { skill_dmg_: c1_moon_dmg_ },
+    illusionDmg: dmgNode('hp', dm.skill.illusionDmg, 'skill', {
```
Comment (nguyentvan7) [inline apps/frontend/src/app/Data/Characters/Nilou/index.tsx:201]: Breaks any multi opts. we can change the dm value, but maybe keep the first illusionDmg instance

File: apps/frontend/src/app/Data/Characters/RaidenShogun/index.tsx [hunk 3]
```diff
@@ -105,12 +105,16 @@ const skillEye_ = equal(
...
   )
 )
-
+const [condInBurstPath, condInBurst] = cond(key, 'InBurst')
 function skillDmg(atkType: number[]) {
   // if Raiden is above or equal to C2, then account for DEF Ignore else not
   return dmgNode('atk', atkType, 'skill', {
     enemy: {
-      defIgn: greaterEq(input.constellation, 2, dm.constellation2.def_ignore),
+      defIgn: greaterEq(
```
Comment (nguyentvan7) [inline apps/frontend/src/app/Data/Characters/RaidenShogun/index.tsx:113]: This should be in the general premod so that all dmg instances are affected by this

File: apps/frontend/src/app/Data/Characters/Shenhe/index.tsx [hunk 4]
```diff
@@ -497,7 +489,16 @@ const sheet: ICharacterSheet = {
     passive1: ct.talentTem('passive1'),
     passive2: ct.talentTem('passive2'),
     passive3: ct.talentTem('passive3'),
-    constellation1: ct.talentTem('constellation1'),
+    constellation1: ct.talentTem('constellation1', [
```
Comment (nguyentvan7) [inline apps/frontend/src/app/Data/Characters/Shenhe/index.tsx:492]: needs to be inside ct.fieldsTem

File: apps/frontend/src/app/Data/Characters/Sucrose/index.tsx [hunk 5]
```diff
@@ -383,7 +383,16 @@ const sheet: ICharacterSheet = {
       }),
     ]),
     passive3: ct.talentTem('passive3'),
-    constellation1: ct.talentTem('constellation1'),
+    constellation1: ct.talentTem('constellation1', [
```
Comment (nguyentvan7) [inline apps/frontend/src/app/Data/Characters/Sucrose/index.tsx:386]: need ct.fieldstem

File: apps/frontend/src/app/Data/Characters/Xiao/index.tsx [hunk 6]
```diff
@@ -366,12 +357,30 @@ const sheet: ICharacterSheet = {
     passive1: ct.talentTem('passive1'),
     passive2: ct.talentTem('passive2'),
     passive3: ct.talentTem('passive3'),
-    constellation1: ct.talentTem('constellation1'),
+    constellation1: ct.talentTem('constellation1', [
```
Comment (nguyentvan7) [inline apps/frontend/src/app/Data/Characters/Xiao/index.tsx:360]: ct.fieldstem

File: apps/frontend/src/app/Data/Characters/YaeMiko/index.tsx [hunk 7]
```diff
@@ -267,33 +318,21 @@ const sheet: ICharacterSheet = {
       { fields: [{ node: dmgFormulas.passive2.nodeAsc4 }] },
     ]),
     passive3: ct.talentTem('passive3'),
-    constellation1: ct.talentTem('constellation1'),
+    constellation1: ct.talentTem('constellation1', [
```
Comment (nguyentvan7) [inline apps/frontend/src/app/Data/Characters/YaeMiko/index.tsx:321]: ct.fieldstem

File: apps/frontend/src/app/Data/Characters/Yelan/index.tsx [hunk 8]
```diff
@@ -432,7 +425,16 @@ const sheet: ICharacterSheet = {
     ]),
     passive2: ct.talentTem('passive2'),
     passive3: ct.talentTem('passive3'),
-    constellation1: ct.talentTem('constellation1'),
+    constellation1: ct.talentTem('constellation1', [
```
Comment (nguyentvan7) [inline apps/frontend/src/app/Data/Characters/Yelan/index.tsx:428]: ct.fieldstem and shouldnt this stay in the skill?

File: apps/frontend/src/app/Data/Weapons/Polearm/CalamityQueller/index.tsx [hunk 9]
```diff
@@ -33,16 +33,9 @@ const dmg_Nodes = Object.fromEntries(
...
 const atkInc = prod(
-  compareEq(
-    input.activeCharKey,
-    input.charKey,
-    constant(1, {
-      /* TODO: Add key for active char */
-    }),
-    constant(2, { name: trm('inactiveKey') })
-  ),
+  constant(1, {}),
```
Comment (nguyentvan7) [inline apps/frontend/src/app/Data/Weapons/Polearm/CalamityQueller/index.tsx:36]: the offfield flag is not used to change the calculation amount anywhere

**Review by nguyentvan7 — CHANGES_REQUESTED** [review]

File: apps/frontend/src/app/Data/Characters/Albedo/index.tsx [hunk 10]
```diff
@@ -382,23 +383,6 @@ const sheet: ICharacterSheet = {
           },
         ],
       },
-      ct.condTem('burst', {
-        value: condBurstBlossom,
-        path: condBurstBlossomPath,
-        name: ct.ch('isotomaOnField'),
```
[the remark this answers is not in the document]
Comment (PolomoPT) [reply apps/frontend/src/app/Data/Characters/Albedo/index.tsx:388]: You mean conditional? Yeah. it's only used to display the dmg node. We want to pull those out of conditionals

File: apps/frontend/src/app/Data/Characters/Amber/index.tsx [hunk 11]
```diff
@@ -399,7 +399,16 @@ const sheet: ICharacterSheet = {
     constellation3: ct.talentTem('constellation3', [
       { fields: [{ node: nodeC3 }] },
     ]),
-    constellation4: ct.talentTem('constellation4'),
+    constellation4: ct.talentTem('constellation4', [
+      {
+        fields: [
```
[the remark this answers is not in the document]
Comment (PolomoPT) [reply apps/frontend/src/app/Data/Characters/Amber/index.tsx:404]: I wanted to try doing this as a standard with additional charges so as to unclutter the Headers under Skills and stuff. Idk, I think you could treat Additional Charges as either belonging to Skills or as common effects, like we do with Talent Boost.

Also, why do we need a ct.fieldsTem? Don't a lot of fieldsTems do this thing i did?

File: apps/frontend/src/app/Data/Characters/Cyno/index.tsx [hunk 12]
```diff
@@ -128,12 +128,6 @@ const a4_bolt_dmgInc = greaterEq(
   prod(percent(dm.passive2.bolt_dmgInc_), input.total.eleMas)
 )
 
-const c1_atkSPD_ = greaterEq(
```
[the remark this answers is not in the document]
Comment (PolomoPT) [reply apps/frontend/src/app/Data/Characters/Cyno/index.tsx:131]: Removed it all because ATK SPD isn't GO-relevant.

File: apps/frontend/src/app/Data/Characters/Bennett/index.tsx [hunk 13]
```diff
@@ -383,12 +387,6 @@ const sheet: ICharacterSheet = {
         states: {
           activeInArea: {
             fields: [
-              {
```
[the remark this answers is not in the document]
Comment (PolomoPT) [reply apps/frontend/src/app/Data/Characters/Bennett/index.tsx:386]: I removed that because it's basically the multiplier — we don't display the multipliers for anything else. Same with C1 ratio.

File: apps/frontend/src/app/Data/Characters/Faruzan/index.tsx [hunk 14]
```diff
@@ -359,19 +360,26 @@ const sheet: ICharacterSheet = {
...
-          {
-            node: c6Benefit_anemo_critDMG_,
-          },
-          {
-            // Only show on Faruzan's page
-            canShow: (data) => data.get(input.activeCharKey).value === key,
-            text: ct.ch('c6Arrow'),
+        path: condC6CritPath,
+        value: condC6Crit,
+        name: ct.ch('baleCondName'),
```
[the remark this answers is not in the document]
Comment (PolomoPT) [reply apps/frontend/src/app/Data/Characters/Faruzan/index.tsx:368]: I confused the two when setting up the `canShow` lmao.

File: apps/frontend/src/app/Data/Characters/KujouSara/index.tsx [hunk 15]
```diff
@@ -251,17 +242,38 @@ const sheet: ICharacterSheet = {
...
+      }),
+      ct.headerTem('passive2', {
+        canShow: equal(condSkillTenguAmbush, 'on', 1),
+        fields: [
+          {
+            node: dmgFormulas.passive2.energyRegen,
+          },
+        ],
+      }),
+      ct.condTem('constellation6', {
```
[the remark this answers is not in the document]
Comment (PolomoPT) [reply apps/frontend/src/app/Data/Characters/KujouSara/index.tsx:267]: no, because one snapshots while the other doesn't. I'd removed the conditional at one point, but then decided otherwise.

File: apps/frontend/src/app/Data/Characters/RaidenShogun/index.tsx (hunk 3 above)
Comment (PolomoPT) [reply apps/frontend/src/app/Data/Characters/RaidenShogun/index.tsx:113]: I tried doing this. It's in my stashed changes; Idk if I did something wrong, but the damages didn't match when I tried running it. Gonna commit so you can tell me if I did anything wrong 😳

File: apps/frontend/src/app/Data/Characters/Cyno/index.tsx [hunk 16]
```diff
@@ -384,68 +409,31 @@ const sheet: ICharacterSheet = {
...
-        canShow: greaterEq(input.asc, 1, 1),
-        fields: [
-          {
-            node: c1_atkSPD_,
-          },
-        ],
-      }),
-    ]),
-
-    passive1: ct.talentTem('passive1', [
```
[the remark this answers is not in the document]
Comment (PolomoPT) [reply apps/frontend/src/app/Data/Characters/Cyno/index.tsx:408]: I think I'm gonna keep this the way I changed it to. I like having it under Skill because it's a new effect granted to the Skill.

File: apps/frontend/src/app/Data/Characters/KujouSara/index.tsx [hunk 17]
```diff
@@ -284,34 +296,28 @@ const sheet: ICharacterSheet = {
...
             text: ct.chg('burst.skillParams.2'),
-            value: `${dm.burst.cd}s`,
+            value: dm.burst.cd,
+            unit: 's',
           },
           {
             text: ct.chg('burst.skillParams.3'),
-            value: `${dm.burst.enerCost}`,
+            value: dm.burst.enerCost,
+            unit: 's',
```
[the remark this answers is not in the document]
Comment (PolomoPT) [reply apps/frontend/src/app/Data/Characters/KujouSara/index.tsx:305]: lmao ig i figured since it did the ``${}`` it was also an `unit: s`

File: apps/frontend/src/app/Data/Characters/KujouSara/index.tsx [hunk 18]
```diff
@@ -284,34 +296,28 @@ const sheet: ICharacterSheet = {
...
+    passive2: ct.talentTem('passive2'),
     passive3: ct.talentTem('passive3'),
     constellation1: ct.talentTem('constellation1'),
     constellation2: ct.talentTem('constellation2', [
       ct.fieldsTem('constellation2', {
         fields: [
           {
             node: infoMut(dmgFormulas.constellation2.dmg, {
-              name: ct.chg(`skill.skillParams.0`),
+              name: st('dmg'),
```
[the remark this answers is not in the document]
Comment (PolomoPT) [reply apps/frontend/src/app/Data/Characters/KujouSara/index.tsx:320]: That's an issue I've noticed with a few conditionals and these damage instances. It feels like it isn't perfect to use the generic strings (like `afterUse.burst` or `dmg`), but also like it's undeserving of a custom name. Maybe I can come back to this later? I feel like it's fine to keep it this way for now.

By the way, I think I mentioned this before, I changed the name because the old one was the Skill's damage name. And they aren't the same.

File: apps/frontend/src/app/Data/Characters/Kirara/index.tsx [hunk 19]
```diff
@@ -470,7 +446,32 @@ const sheet: ICharacterSheet = {
     passive2: ct.talentTem('passive2'),
     passive3: ct.talentTem('passive3'),
     constellation1: ct.talentTem('constellation1'),
-    constellation2: ct.talentTem('constellation2'),
+    constellation2: ct.talentTem('constellation2', [
```
[the remark this answers is not in the document]
Comment (PolomoPT) [reply apps/frontend/src/app/Data/Characters/Kirara/index.tsx:449]: oooh i now see the use of those.

File: apps/frontend/src/app/Data/Characters/Beidou/index.tsx [hunk 20]
```diff
@@ -87,11 +88,11 @@ const dm = {
   },
 } as const
 
-//Toggable stuff:
+//Toggleable stuff:
 // A4: Unleashing <b>Tidecaller</b> with its maximum DMG Bonus
-// C6: During the duration of <b>Stormbreaker</b>
+// Burst: During the duration of <b>Stormbreaker</b>
 
-const [condC6Path, condC6] = cond(key, 'Constellation6')
```
[the remark this answers is not in the document]
Comment (PolomoPT) [reply apps/frontend/src/app/Data/Characters/Beidou/index.tsx:94]: any better way to do this? 🤔

File: apps/frontend/src/app/Data/Characters/Amber/index.tsx (hunk 11 above)
[the remark this answers is not in the document]
Comment (nguyentvan7) [reply apps/frontend/src/app/Data/Characters/Amber/index.tsx:404]: If you want to keep it under the constellation, then we should update the string to mention the skill at least "Additional Skill Charges" or something

[the remark this answers is not in the document]
Comment (PolomoPT) [reply apps/frontend/src/app/Data/Characters/Amber/index.tsx:404]: image
already did, ehe

File: apps/frontend/src/app/Data/Weapons/Polearm/CalamityQueller/index.tsx [hunk 21]
```diff
@@ -33,7 +33,6 @@ const dmg_Nodes = Object.fromEntries(
   ])
 )
 const atkInc = prod(
```
[the remark this answers is not in the document]
Comment (nguyentvan7) [reply apps/frontend/src/app/Data/Weapons/Polearm/CalamityQueller/index.tsx:35]: Then change the premod to be premod: { atk: sum(atkInc, atkIncOffField) } }

[the remark this answers is not in the document]
Comment (nguyentvan7) [reply apps/frontend/src/app/Data/Weapons/Polearm/CalamityQueller/index.tsx:35]: Then change the offfield conditional to display atkIncOffField

**Review by nguyentvan7 — CHANGES_REQUESTED** [review]

File: apps/frontend/src/app/Data/Characters/RaidenShogun/index.tsx [hunk 22]
```diff
@@ -546,6 +532,14 @@ const sheet: ICharacterSheet = {
           },
         },
       }),
+      ct.headerTem('constellation2', {
+        canShow: equal(condInBurst, 'on', 1),
```
[the remark this answers is not in the document]
Comment (PolomoPT) [reply apps/frontend/src/app/Data/Characters/RaidenShogun/index.tsx:536]: i think we do, because the def ignore is only active when in Burst, right?

File: apps/frontend/src/app/Data/Characters/KujouSara/index.tsx [hunk 23]
```diff
@@ -250,7 +250,9 @@ const sheet: ICharacterSheet = {
           TenguJuuraiAmbush: {
             fields: [
               {
-                node: skillTenguAmbush_,
+                node: infoMut(skillTenguAmbush_disp, {
+                  name: st(`increase.atk`),
```
Comment (nguyentvan7) [inline apps/frontend/src/app/Data/Characters/KujouSara/index.tsx:254]: shouldnt this just use keymap.info('atk')?

File: apps/frontend/src/app/Data/Weapons/Polearm/CalamityQueller/index.tsx [hunk 24]
```diff
@@ -32,18 +35,22 @@ const dmg_Nodes = Object.fromEntries(
     subscript(input.weapon.refineIndex, dmg_),
   ])
 )
-const atkInc = prod(
-  lookup(
-    condStacks,
-    objectKeyMap(range(1, 6), (i) => constant(i, { name: st('stacks') })),
-    0
+const atkInc = {
```
Comment (nguyentvan7) [inline apps/frontend/src/app/Data/Weapons/Polearm/CalamityQueller/index.tsx:38]: You don't need the {... } around it

File: apps/frontend/src/app/Data/Characters/RaidenShogun/index.tsx [hunk 25]
```diff
@@ -277,6 +262,7 @@ export const data = dataObjForCharacterSheet(
       burstBoost: nodeC3,
       burst_dmg_: skillEye_,
       electro_dmg_: dmgFormulas.passive2.passive2ElecDmgBonus,
+      enemyDefIgn_: defIgn_
```
Comment (nguyentvan7) [inline apps/frontend/src/app/Data/Characters/RaidenShogun/index.tsx:265]: probably needs to be premod: { enemy: defIgn_ }

**Review by nguyentvan7 — CHANGES_REQUESTED** [review]

File: apps/frontend/src/app/Data/Characters/KujouSara/index.tsx (hunk 23 above)
Comment (PolomoPT) [reply apps/frontend/src/app/Data/Characters/KujouSara/index.tsx:254]: ig so, then. did it to Bennett too.

File: apps/frontend/src/app/Data/Characters/RaidenShogun/index.tsx (hunk 25 above)
Comment (PolomoPT) [reply apps/frontend/src/app/Data/Characters/RaidenShogun/index.tsx:265]: seems like it's indeed that, just defIgn rather than defIgn_

File: apps/frontend/src/app/Data/Characters/Bennett/index.tsx [hunk 26]
```diff
@@ -90,34 +91,32 @@ const dm = {
...
-const activeInAreaAtkDisp = prod(atkIncRatio, input.base.atk)
-
 const [condInAreaPath, condInArea] = cond(key, 'activeInArea')
 const activeInArea = equal(
   'activeInArea',
   condInArea,
   equal(input.activeCharKey, target.charKey, 1)
 )
+const activeInAreaAtkDisp = {
+  ...sum(burstAddlAtk, c1AddlAtk),
```
Comment (nguyentvan7) [inline apps/frontend/src/app/Data/Characters/Bennett/index.tsx:113]: We separated these on purpose because the UI is confusing when combined. The C1 header indicates it is adding more atk, but its actually already factored into the calculation

File: apps/frontend/src/app/Data/Characters/KujouSara/index.tsx [hunk 27]
```diff
@@ -80,7 +81,8 @@ const atkIncRatio = subscript(
 const skillTenguAmbush_disp = equal(
   'TenguJuuraiAmbush',
   condSkillTenguAmbush,
-  prod(input.base.atk, atkIncRatio)
+  prod(input.base.atk, atkIncRatio),
+  KeyMap.info('atk')
```
Comment (nguyentvan7) [inline apps/frontend/src/app/Data/Characters/KujouSara/index.tsx:85]:
```suggestion
  { ...KeyMap.info('atk'), isTeamBuff: true }
```

File: apps/frontend/src/app/Data/Weapons/Polearm/CalamityQueller/index.tsx [hunk 28]
```diff
@@ -60,8 +61,21 @@ const sheet: IWeaponSheet = {
       fields: Object.values(dmg_Nodes).map((node) => ({ node })),
     },
     {
-      value: condStacks,
-      path: condStacksPath,
+      canShow: unequal(condStack, undefined, 1),
```
Comment (nguyentvan7) [inline apps/frontend/src/app/Data/Weapons/Polearm/CalamityQueller/index.tsx:64]: Move this conditional to be underneath the stack conditional

**Review by nguyentvan7 — CHANGES_REQUESTED** [review]
Also fix your merge conflicts

File: apps/frontend/src/app/Data/Characters/Bennett/index.tsx (hunk 26 above)
Comment (PolomoPT) [reply apps/frontend/src/app/Data/Characters/Bennett/index.tsx]: So what I did was change the C1 listing to instead talk about the buff it gives. I think this should be clear enough.

It's gonna display like this: 
image
tell me what you think :3

File: apps/frontend/src/app/Data/Characters/KujouSara/index.tsx [hunk 29]
```diff
@@ -275,6 +275,7 @@ const sheet: ICharacterSheet = {
         value: condC6,
         path: condC6Path,
         teamBuff: true,
+        canShow: equal(condSkillTenguAmbush, 'TenguJuuraiAmbush', 1),
```
Comment (nguyentvan7) [inline apps/frontend/src/app/Data/Characters/KujouSara/index.tsx:278]: If we are tying this buff to this conditional, then you also need to update the buff logic on line 94

File: apps/frontend/src/app/Data/Characters/Mika/index.tsx [hunk 30]
```diff
@@ -121,7 +121,7 @@ const a1DetectorStacks_physical_dmg_ = equal(
   target.charKey,
   a1DetectorStacks_physical_dmg_disp
 )
-
+const [condC6CritPath, condC6Crit] = cond(key, 'c6Crit')
```
Comment (nguyentvan7) [inline apps/frontend/src/app/Data/Characters/Mika/index.tsx:124]: You're not using this for buff calculation

Comment (nguyentvan7) [reply apps/frontend/src/app/Data/Characters/Mika/index.tsx:124]: I don't think his C6 needs a cond actually, isn't the condition the same as inSoulWind?

File: libs/localization/assets/locales/en/sheet.json [hunk 31]
```diff
@@ -153,7 +150,9 @@
     "electro": "After triggering an <electro>Electro-related</electro> Elemental Reaction"
   },
   "bonusScaling": {
-    "skill_": "Ele. Skill Bonus Scaling"
+    "skill_": "Ele. Skill Bonus Scaling",
+    "atkInc": "ATK Inc. Bonus Scaling",
+    "percentStat": "{{percent}} {{stat}}"
```
Comment (nguyentvan7) [inline libs/localization/assets/locales/en/sheet.json:155]: Is this something that can work for all languages?

File: apps/frontend/src/app/Data/Characters/Noelle/index.tsx [hunk 32]
```diff
@@ -402,7 +398,11 @@ const sheet: ICharacterSheet = {
         canShow: equal(condBurst, 'on', 1),
         fields: [
           {
-            node: nodeC6Atk,
+            text: st('bonusScaling.atkInc'),
+            value: st('bonusScaling.percentStat', {
+              percent: `${dm.constellation6.burstAtkBonus * 100}%`,
+              stat: 'DEF',
```
Comment (nguyentvan7) [inline apps/frontend/src/app/Data/Characters/Noelle/index.tsx:404]: Untranslated string

File: apps/frontend/src/app/Data/Characters/Bennett/index.tsx [hunk 33]
```diff
@@ -398,8 +398,11 @@ const sheet: ICharacterSheet = {
       ct.headerTem('constellation1', {
         fields: [
           {
-            text: ct.ch('additionalATK.name'),
-            value: ct.ch('additionalATK.value'),
+            text: st('bonusScaling.atkInc'),
+            value: st('bonusScaling.percentStat', {
+              percent: `${dm.constellation1.atk_inc * 100}%`,
+              stat: 'Base ATK',
```
Comment (nguyentvan7) [inline apps/frontend/src/app/Data/Characters/Bennett/index.tsx:404]: Untranslated string

**Review by nguyentvan7 — CHANGES_REQUESTED** [review]

File: apps/frontend/src/app/Data/Characters/Mika/index.tsx (hunk 30 above)
Comment (PolomoPT) [reply apps/frontend/src/app/Data/Characters/Mika/index.tsx:124]: yeah, but while the regular buff snapshots, CRIT from C6 does not[citation needed] (but it shouldn't, like other crit buffs)

Comment (PolomoPT) [reply apps/frontend/src/app/Data/Characters/Mika/index.tsx:124]: oh, wait, i'm not sure if the regular buff snapshots

File: libs/localization/assets/locales/en/sheet.json (hunk 31 above)
Comment (PolomoPT) [reply libs/localization/assets/locales/en/sheet.json:155]: It could, in theory; turns out the issue is another, however: `[object Object]` 😭

Comment (nguyentvan7) [reply libs/localization/assets/locales/en/sheet.json:155]: Yes that is the issue with nesting translation, we had this issue before. Anyways, this percent stat thing shouldnt be like this. Instead we should be using a node with 
```
{
  text: st(stat.statName),
  value: percentValue
}
```

Comment (PolomoPT) [reply libs/localization/assets/locales/en/sheet.json:155]: i'm fixing it. just took a break because i got involved with something

File: libs/dm-localization/src/lib/Data/sheet.ts [hunk 34]
```diff
@@ -84,12 +89,21 @@ const data = {
...
-    bloom: 3593652061, // or maybe it is 4074539307
+    bloom: 1216168406,
     burgeon: 2021015747,
     hyperbloom: 2697794115,
     quicken: 347446227,
     aggravate: 2961120579,
-    spread: 2191579811, // or maybe it is 982642368
+    spread: 2191579811,
+  },
+  stat: {
```
Comment (PolomoPT) [inline libs/dm-localization/src/lib/Data/sheet.ts:99]: i only added the necessary things because i'm gonna work with this further in another PR. Will leave the bulk of changes until then.

File: libs/localization/assets/locales/en/sheet.json [hunk 35]
```diff
@@ -152,7 +152,7 @@
   "bonusScaling": {
     "skill_": "Ele. Skill Bonus Scaling",
     "atkInc": "ATK Inc. Bonus Scaling",
-    "percentStat": "{{percent}} {{stat}}"
```
Comment (nguyentvan7) [inline libs/localization/assets/locales/en/sheet.json]: Do we really need a translated string for this? why not add the % ourselves in the sheet?

Comment (PolomoPT) [reply libs/localization/assets/locales/en/sheet.json]: i think you commented on an old version of the file. Anyways, I'm actually doing this to give the option for translations to add connectives (pretty sure some languages will want to do the equivalent of adding an "of" in there.

uhhh i think i have other reasons but i can only think of this one right now and i think it's good enough

**Review by nguyentvan7 — DISMISSED** [review]

**Review by nguyentvan7 — APPROVED** [review]

**Review by frzyc — APPROVED** [review]
