### PR TITLE
Fix potential error boundary

### LINKED ISSUE #1038: Error on certain load boundaries
```
Message: Cannot read properties of undefined (reading 'mainStatKey')
Name: TypeError
Stack: TypeError: Cannot read properties of undefined (reading 'mainStatKey')
    at d (https://frzyc.github.io/genshin-optimizer/main.97cda89837a00a99.js:125:1089094)
    at https://frzyc.github.io/genshin-optimizer/476.a8ec997585000bfd.js:1:32771
    at Array.map (<anonymous>)
    at x (https://frzyc.github.io/genshin-optimizer/476.a8ec997585000bfd.js:1:32755)
    at y (https://frzyc.github.io/genshin-optimizer/476.a8ec997585000bfd.js:1:31910)
    at https://frzyc.github.io/genshin-optimizer/476.a8ec997585000bfd.js:1:31542
    at https://frzyc.github.io/genshin-optimizer/476.a8ec997585000bfd.js:1:31723
    at Object.useMemo (https://frzyc.github.io/genshin-optimizer/main.97cda89837a00a99.js:125:7423982)
    at t.useMemo (https://frzyc.github.io/genshin-optimizer/main.97cda89837a00a99.js:125:7536119)
    at C (https://frzyc.github.io/genshin-optimizer/476.a8ec997585000bfd.js:1:31395)
```
Error probably originated here:
https://github.com/frzyc/genshin-optimizer/blob/master/apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/index.tsx#L504
image

need to sanitize the `buildArts` array to check for invalid artifacts.

### PR DESCRIPTION
**Pull request by frzyc**
fix #1038

### CODE REVIEW

File: apps/frontend/src/app/Database/DataManagers/BuildSettingData.ts [hunk 1]
```diff
@@ -93,7 +93,7 @@ const initialBuildSettings: BuildSetting = deepFreeze({
   optimizationTarget: undefined,
   mainStatAssumptionLevel: 0,
   allowLocations: [],
-  allowPartial: false,
+  allowPartial: true,
```
Comment (nguyentvan7) [inline apps/frontend/src/app/Database/DataManagers/BuildSettingData.ts:96]: Sneaking this in here is interesting. Enabling this by default messes up the graph display in an annoying way. Also random since this doesn't look like it should be in this PR

**Review by nguyentvan7 — CHANGES_REQUESTED** [review]

File: apps/frontend/src/app/Database/DataManagers/BuildSettingData.ts (hunk 1 above)
Comment (frzyc) [reply apps/frontend/src/app/Database/DataManagers/BuildSettingData.ts:96]: This error is actually created by partial builds, so its kind of related. How does this mess up the graph? like crash, or just create clusters at low ranges of the graph?

Comment (frzyc) [reply apps/frontend/src/app/Database/DataManagers/BuildSettingData.ts:96]: Now realized the annoyance, I guess this should be off by default for now.

Comment (nguyentvan7) [reply apps/frontend/src/app/Database/DataManagers/BuildSettingData.ts:96]: image
yea just clusters at the bottom end, so y-axis is all messed up

**Review by nguyentvan7 — APPROVED** [review]
Why force push, especially after I leave a review? the history is good to have, even if its just you calling `git revert HEAD` or something

**Comment by frzyc** [comment]
> Why force push, especially after I leave a review? the history is good to have, even if its just you calling `git revert HEAD` or something

Comments on PR still exist.

**Comment by nguyentvan7** [comment]
Comment still exists but for larger commits or something, the full context is gone. My comment looks disjointed from the PR. It's generally in bad taste to rewrite history for things that are already public, tho I can understand for large rebases or something
