### PR TITLE
BuildDisplayItem fixes for build comparisons done from character editor

### LINKED ISSUE #1802: Unable to compare to current build when swapping gear through the character editor
https://github.com/frzyc/genshin-optimizer/assets/47800040/6ca796e2-0540-4756-bae5-7ea1a45b20cc

This issue only occurs when going through the character editor specifically and happens with both artifacts and weapons. Doing it on live results in a crash, doing it in dev mode on ToT master results in the swap modal closing and no comparison shown.

### PR DESCRIPTION
**Pull request by arquelion**
## Describe your changes
In `BuildDisplayItem.tsx`:
- Added boolean `compareFromCharEditor` tracking whether `buildType ` is undefined - Due to `buildType` being pulled from `TeamCharacterContext`, this value is undefined when build comparisons are made from the character editor, which is the only other location which currently uses `BuildDisplayItem`.
- Modified logic for `activeArtifacts` and `activeWeapon` to return the weapon/artifacts in Equipped when `compareFromCharEditor` is `true`
- Added prop to `compareArtifactModal` for the bool indicating whether this is a build comparison from the character editor - This value is used to disable rendering the artifact and character inclusion/exclusion buttons as these make little sense when not in the Optimize tab.

In `EquipBuildModal.tsx`:
- `characterKey` is now pulled from `CharacterContext` instead of `TeamCharacterContext` to account for the possibility of access from outside the Teams tab where `characterKey` would otherwise be undefined
- Option to copy current equipment is no longer present when comparing/equipping through the character editor

## Issue or discord link

- Resolves #1802 

## Testing/validation
Manually checked from editor in Characters tab and confirmed behavior when working within a team remains unaffected.

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [x] I have commented my code in hard-to understand areas.
- [x] I have made corresponding changes to README or wiki.
- [x] For front-end changes, I have updated the corresponding English translations.
- [x] I have run `yarn run mini-ci` locally to validate format and lint.
- [x] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

### CODE REVIEW

**Comment by arquelion** [comment]
Is late, will add validation images later if we still want them.

File: apps/frontend/src/app/PageTeam/CharacterDisplay/Tabs/TabOptimize/Components/BuildDisplayItem.tsx [hunk 1]
```diff
@@ -245,23 +245,43 @@ export default function BuildDisplayItem({
...
 
+  // An undefined buildType indicates this was accessed from outside a team. This currently occurs
+  // when comparing from the character editor.
+  const compareFromCharEditor = buildType === undefined
+
   const activeWeapon = useMemo(() => {
     if (dbDirty && buildType === 'real')
       return database.builds.get(buildId)!.weaponId
     if (dbDirty && buildType === 'equipped') return equippedWeapon
+    if (compareFromCharEditor) return equippedWeapon
```
Comment (frzyc) [inline apps/frontend/src/app/PageTeam/CharacterDisplay/Tabs/TabOptimize/Components/BuildDisplayItem.tsx:256]: I'd recommend hoisting this up to the first line in the function

File: apps/frontend/src/app/PageTeam/CharacterDisplay/Tabs/TabOptimize/Components/BuildDisplayItem.tsx [hunk 2]
```diff
@@ -245,23 +245,43 @@ export default function BuildDisplayItem({
...
+    buildId,
+    equippedWeapon,
+    compareFromCharEditor,
+  ])
 
   const activeArtifacts = useMemo(() => {
     if (dbDirty && buildType === 'real')
       return database.builds.get(buildId)!.artifactIds
     if (dbDirty && buildType === 'equipped') return equippedArtifacts
+    if (compareFromCharEditor) return equippedArtifacts
```
Comment (frzyc) [inline apps/frontend/src/app/PageTeam/CharacterDisplay/Tabs/TabOptimize/Components/BuildDisplayItem.tsx:273]: I'd recommend hoisting this up to the first line in the function

**Review by frzyc — CHANGES_REQUESTED** [review]
2 minor change, otherwise LGTM

File: apps/frontend/src/app/PageTeam/CharacterDisplay/Tabs/TabOptimize/Components/BuildDisplayItem.tsx (hunk 1 above)
Comment (arquelion) [reply apps/frontend/src/app/PageTeam/CharacterDisplay/Tabs/TabOptimize/Components/BuildDisplayItem.tsx]: done

File: apps/frontend/src/app/PageTeam/CharacterDisplay/Tabs/TabOptimize/Components/BuildDisplayItem.tsx (hunk 2 above)
Comment (arquelion) [reply apps/frontend/src/app/PageTeam/CharacterDisplay/Tabs/TabOptimize/Components/BuildDisplayItem.tsx]: done

**Review by frzyc — APPROVED** [review]
