### PR TITLE
Hide undesirable sections in target selectors

### LINKED ISSUE #2109: Having an invalid build constraint will crash the Artifact Upgrader tab
image

[message.json](https://github.com/frzyc/genshin-optimizer/files/15285886/message.json)

Go to Neuvi -> Artifact Upgrader -> Crash

### LINKED ISSUE #2126: Opt target selector allows selecting received team buffs
image

### PR DESCRIPTION
**Pull request by frzyc**
## Describe your changes

Add all the additional sections to the disallow section list.
Also proactively add the "character" section from https://github.com/frzyc/genshin-optimizer/pull/2160 to the blacklist.

## Issue or discord link

- Resolves #2126
- Resolves #2109

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [ ] I have commented my code in hard-to understand areas.
- [ ] I have made corresponding changes to README or wiki.
- [ ] For front-end changes, I have updated the corresponding English translations.
- [ ] I have run `yarn run mini-ci` locally to validate format and lint.
- [ ] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

### CODE REVIEW

File: libs/gi/page-team/src/CharacterDisplay/Tabs/TabOptimize/Components/OptimizationTargetEditorList.tsx [hunk 1]
```diff
@@ -172,6 +172,9 @@ function OptimizationTargetEditorItem({
         setTarget={(target) => setTarget(target, path, index)}
         defaultText={t('targetSelector.selectBuildTarget')}
         disabled={disabled}
+        targetSelectorModalProps={{
+          excludeSections: ['custom', 'bounsStats', 'character', 'teamBuff'],
```
Comment (nguyentvan7) [inline libs/gi/page-team/src/CharacterDisplay/Tabs/TabOptimize/Components/OptimizationTargetEditorList.tsx:176]: Why no multi opt for min stat?

**Review by nguyentvan7 — APPROVED** [review]

File: libs/gi/page-team/src/CharacterDisplay/Tabs/TabOptimize/Components/OptimizationTargetEditorList.tsx (hunk 1 above)
Comment (frzyc) [reply libs/gi/page-team/src/CharacterDisplay/Tabs/TabOptimize/Components/OptimizationTargetEditorList.tsx:176]: mtargets can have some funky targets inside(since no specific target validation), and they can cause shifts when editing mtarget list (referenced by index), a lot of cornercases for a usecase that I don't really see any nuance in
