### PR TITLE
Fix team filter

### LINKED ISSUE #1737: Team member filter is not working
After the recent patch if you filter by team member, no teams appear.

Example below indicates Xingqiu has 4 teams, but nothing shows:
image

### PR DESCRIPTION
**Pull request by nguyentvan7**
## Issue or discord link

- Resolve #1737

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [ ] I have commented my code in hard-to understand areas.
- [ ] I have made corresponding changes to README or wiki.
- [ ] For front-end changes, I have updated the corresponding English translations.
- [ ] I have run `yarn run mini-ci` locally to validate format and lint.
- [ ] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

### CODE REVIEW

File: apps/frontend/src/app/PageTeams/TeamSort.ts [hunk 1]
```diff
@@ -31,16 +31,19 @@ export function teamFilterConfigs(
   database: ArtCharDatabase
 ): TeamFilterConfigs {
   return {
-    charKeys: (teamId: string, filter: CharacterKey[]) =>
-      !filter.length ||
-      !!database.teams
+    charKeys: (teamId: string, filter: CharacterKey[]) => {
+      const nonEmptyLoadoutData = database.teams
```
Comment (frzyc) [inline apps/frontend/src/app/PageTeams/TeamSort.ts:35]:
```suggestion
      if(!filter.length) return true
      const nonEmptyLoadoutData = database.teams
```

**Review by frzyc — CHANGES_REQUESTED** [review]
One nit, otherwise LGTM

**Review by frzyc — APPROVED** [review]
