### PR TITLE
Artifact & Character exclusion build settings are now per character

### LINKED ISSUE #901: Artifact exclusion per character
1. artifact exclusion as a global toggle only affects "optimize" behaviour, so having it on the artifact page is only beneficial because of the artifact filter UI(to find artifacts), but its too far from the "optimize" tab so its not a good UI flow.
2. most of the options on the "optimize" page seems to also exclude artifacts (on a character basis). 
3. this creates a disconnect with the global exclusion vs the per-character exclusion on the "optimize" page, since they are set at two different UI.

The proposal here is to remove the "global" artifact exclusion, in favor of being able to select artifact exclusion in addition to the ones filtered by the optimize config.

### LINKED ISSUE #991: Multiple entries when merging `unique` for key art,plume,id
Upload attached DB and navigate to Ayaka's optimize page. On Prod, look at the console. On dev, the page will crash
[Van_2023-02-14_04-56-16 - Copy.txt](https://github.com/frzyc/genshin-optimizer/files/10751907/Van_2023-02-14_04-56-16.-.Copy.txt)

### PR DESCRIPTION
**Pull request by frzyc**
* Resolve #901 
* Fix #991 
image
image
image

### CODE REVIEW

File: apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/Components/BuildDisplayItem.tsx [hunk 1]
```diff
@@ -125,12 +130,29 @@ function CompareArtifactModal({ newOld: { newId, oldId }, mainStatAssumptionLeve
...
+function ExcludeButton({ id }: { id: string }) {
+  const { t } = useTranslation("artifact")
+  const { character: { key: characterKey } } = useContext(CharacterContext)
+  const { buildSetting: { artExclusion }, buildSettingDispatch } = useBuildSetting(characterKey)
+  const excluded = artExclusion.includes(id)
+  const toggle = useCallback(() => excluded ? buildSettingDispatch({ artExclusion: artExclusion.filter(i => i !== id) }) : buildSettingDispatch({ artExclusion: [...artExclusion, id] }), [id, excluded, artExclusion, buildSettingDispatch])
+
+  return <BootstrapTooltip title={<Box>
+    <Typography>{t`excludeArtifactTip`}</Typography>
+    <Typography><ColorText color={excluded ? "error" : "success"}>{t(`:${excluded ? "excluded" : "included"}`)}</ColorText></Typography>
```
Comment (nguyentvan7) [inline apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/Components/BuildDisplayItem.tsx:151]: Translation not working correctly

File: apps/frontend/src/app/Database/DataManagers/BuildSettingData.ts [hunk 2]
```diff
@@ -1,7 +1,7 @@
 import Artifact from "../../Data/Artifacts/Artifact";
 import { maxBuildsToShowDefault, maxBuildsToShowList } from "../../PageCharacter/CharacterDisplay/Tabs/TabOptimize/Build";
 import { MainStatKey } from "../../Types/artifact";
-import { allCharacterKeys, ArtifactSetKey, CharacterKey } from "../../Types/consts";
+import { allCharacterKeys, ArtifactSetKey, CharacterKey } from "@genshin-optimizer/consts";
```
Comment (nguyentvan7) [inline apps/frontend/src/app/Database/DataManagers/BuildSettingData.ts:4]: nit: this should be top import

File: apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/Components/UseExcluded.tsx [hunk 3]
```diff
@@ -1,23 +1,119 @@
...
+import ArtifactCard from "../../../../../PageArtifact/ArtifactCard";
+import { artifactFilterConfigs, initialFilterOption } from "../../../../../PageArtifact/ArtifactSort";
+import useBoolState from "../../../../../ReactHooks/useBoolState";
+import useForceUpdate from "../../../../../ReactHooks/useForceUpdate";
+import useMediaQueryUp from "../../../../../ReactHooks/useMediaQueryUp";
+import { filterFunction } from "../../../../../Util/SortByFilters";
 import useBuildSetting from "../useBuildSetting";
 
-export default function UseExcluded({ disabled = false, artsDirty }: { disabled?: boolean, artsDirty: object }) {
+export default function UseExcluded({ disabled = false }: { disabled?: boolean }) {
```
Comment (nguyentvan7) [inline apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/Components/UseExcluded.tsx:24]: While we are here, can we rename this so it doesn't sound like a react hook?

File: apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/Components/UseEquipped.tsx [hunk 4]
```diff
@@ -18,7 +19,7 @@ import useCharacter from "../../../../../ReactHooks/useCharacter";
 import useCharSelectionCallback from "../../../../../ReactHooks/useCharSelectionCallback";
 import { ICachedArtifact } from "../../../../../Types/artifact";
 import { ICachedCharacter } from "../../../../../Types/character";
-import { CharacterKey, charKeyToLocCharKey } from "../../../../../Types/consts";
+import { charKeyToLocCharKey } from "../../../../../Types/consts";
 import useBuildSetting from "../useBuildSetting";
 const CharacterSelectionModal = React.lazy(() => import('../../../../CharacterSelectionModal'))
```
Comment (nguyentvan7) [inline apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/Components/UseEquipped.tsx:25]: Can we also rename this so it doesn't sound like a react hook?

File: apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/Components/UseExcluded.tsx [hunk 5]
```diff
@@ -1,23 +1,119 @@
...
+              <ArtifactCardNano artifactId={id} slotKey="flower" BGComponent={CardLight} onClick={() => onDelSelect(id)} showLocation />
+            </Grid>)}
+        </Grid>
+      </CardContent>
+    </CardDark ></ModalWrapper>
+    <ButtonGroup>
+      <Button fullWidth onClick={() => buildSettingDispatch({ useExcludedArts: !useExcludedArts })} disabled={disabled} startIcon={useExcludedArts ? <CheckBox /> : <CheckBoxOutlineBlank />} color={useExcludedArts ? "success" : "secondary"}>
+        <Box sx={{ display: "flex", gap: 1 }}>
+          <Box><Trans t={t} i18nKey="useExcluded.title" count={numExcludedArt}>Use Excluded Artifacts</Trans></Box>
+          {useExcludedArts ? <SqBadge color="error"><Trans t={t} i18nKey="useExcluded.excNum" count={numExcludedArt}>Excluded <strong>{{ count: numExcludedArt } as TransObject}</strong> artifacts</Trans></SqBadge> :
```
Comment (nguyentvan7) [inline apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/Components/UseExcluded.tsx:58]: Ternary is backwards
image

File: apps/frontend/src/app/Database/DataManagers/BuildSettingData.ts [hunk 6]
```diff
@@ -62,17 +64,21 @@ export class BuildSettingDataManager extends DataManager<CharacterKey, "buildSet
     if (!optimizationTarget || !Array.isArray(optimizationTarget)) optimizationTarget = undefined
     if (typeof mainStatAssumptionLevel !== "number" || mainStatAssumptionLevel < 0 || mainStatAssumptionLevel > 20)
       mainStatAssumptionLevel = 0
+
+    if (!artExclusion || !Array.isArray(artExclusion)) artExclusion = []
+    else artExclusion = [...(new Set(artExclusion))].filter(id => this.database.arts.keys.includes(id))
```
Comment (nguyentvan7) [inline apps/frontend/src/app/Database/DataManagers/BuildSettingData.ts:69]: Wasn't there a past issue where artifact IDs would get jumbled on import of a scan? I can't replicate it now, so not sure if it is still an issue. But if so, this would cause different artifacts to be excluded if the IDs are changed

**Review by nguyentvan7 — CHANGES_REQUESTED** [review]

**Comment by nguyentvan7** [comment]
I predict people will want some way to easily globally exclude (and then include on a specific character or something). There is no easy way to do that in this branch

**Comment by nguyentvan7** [comment]
I also predict some people may be annoyed at losing all their exclusion data with this change

File: apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/Components/UseExcluded.tsx [hunk 7]
```diff
@@ -1,23 +1,119 @@
...
+  const onSelect = useCallback((id: string) => {
+    buildSettingDispatch({ artExclusion: [...artExclusion, id] })
+  }, [buildSettingDispatch, artExclusion])
+  const onDelSelect = useCallback((id: string) => {
+    buildSettingDispatch({ artExclusion: artExclusion.filter(i => i !== id) })
+  }, [buildSettingDispatch, artExclusion])
+  return <>
+    <ModalWrapper open={show} onClose={onClose} containerProps={{ maxWidth: "xl" }}><CardDark>
+      <CardContent>
+        <Typography>{t`useExcluded.title`}</Typography>
```
Comment (nguyentvan7) [inline apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/Components/UseExcluded.tsx:40]: Can you make this look better (see the header for UseEquipped)

File: apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/Components/UseExcluded.tsx [hunk 8]
```diff
@@ -1,23 +1,119 @@
...
+        <Divider />
```
Comment (nguyentvan7) [inline apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/Components/UseExcluded.tsx:41]: Should we add a little info blurb that mentions this is per-character now?

**Review by nguyentvan7 — CHANGES_REQUESTED** [review]

File: apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/Components/UseExcluded.tsx (hunk 3 above)
Comment (frzyc) [reply apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/Components/UseExcluded.tsx:24]: (nit-back) react hooks are `use...` and this is `Use...`

File: apps/frontend/src/app/Database/DataManagers/BuildSettingData.ts (hunk 6 above)
Comment (frzyc) [reply apps/frontend/src/app/Database/DataManagers/BuildSettingData.ts:69]: oh right i need to add this to the import list to migrate

**Review by nguyentvan7 — CHANGES_REQUESTED** [review]
Buncha string changes

File: apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/Components/ExcludeArt.tsx [hunk 9]
```diff
@@ -0,0 +1,121 @@
...
+const numToShowMap = { xs: 2 * 3, sm: 2 * 3, md: 3 * 3, lg: 4 * 3, xl: 4 * 3 }
+const filterOptionReducer = (state, action) => ({ ...state, ...action })
+function ArtifactSelectModal({ onSelect, show, onClose, artExclusion }:
+  { onSelect: (id: string) => void, show: boolean, onClose: () => void, artExclusion: string[] }) {
+  const { t } = useTranslation("page_character_optimize")
+  const { database } = useContext(DatabaseContext)
+  const clickHandler = useCallback((id: string) => {
+    onSelect(id)
+    onClose()
+    console.log({ id })
```
Comment (nguyentvan7) [inline apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/Components/ExcludeArt.tsx:78]: log

File: libs/localization/assets/locales/en/page_character_optimize.json [hunk 10]
```diff
@@ -22,29 +22,29 @@
...
-      "usingNum_one": "Using artifacts from <1>{{count}}</1> character",
-      "usingNum_other": "Using artifacts from <1>{{count}}</1> unlisted characters",
-      "status": {
-        "use": "Use artifacts",
-        "dont": "Don't use artifacts",
-        "curr": "Current character"
-      },
-      "add": "Add character to list",
-      "clearList": "Clear List"
+      "title_sel": "Allow equipped artifacts",
```
Comment (nguyentvan7) [inline libs/localization/assets/locales/en/page_character_optimize.json:42]:
```suggestion
```
Remove this string and just use "excludeChar.title" for the title of the modal

File: apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/Components/AllowChar.tsx [hunk 11]
```diff
@@ -0,0 +1,111 @@
...
+
+  const toggle = useCallback((lk: LocationKey) => buildSettingDispatch({ allowLocations: toggleArr(allowLocations, lk) }), [allowLocations, buildSettingDispatch])
+
+  const total = locList.length
+  const useTot = allowLocations.length
+  return <Box display="flex" gap={1}>
+    <ModalWrapper open={show} onClose={onClose} containerProps={{ maxWidth: "xl" }}><CardDark>
+      <CardContent>
+        <Box display="flex" gap={1} >
+          <Typography variant="h6" flexGrow={1}>{t`excludeChar.modal.title_sel`}</Typography>
```
Comment (nguyentvan7) [inline apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/Components/AllowChar.tsx:62]:
```suggestion
          <Typography variant="h6" flexGrow={1}>{t`excludeChar.modal.title`}</Typography>
```

Comment (nguyentvan7) [reply apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/Components/AllowChar.tsx:62]: Do you want to add a tooltip like for Exclude Artifacts? Maybe its simple enough, just pointing out any differences between the two

File: apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/Components/AllowChar.tsx [hunk 12]
```diff
@@ -0,0 +1,111 @@
...
+  const { buildSetting: { allowLocations }, buildSettingDispatch } = useBuildSetting(characterKey)
+  const { database } = useContext(DatabaseContext)
+  const [show, onOpen, onClose] = useBoolState(false)
+  const [dbDirty, forceUpdate] = useForceUpdate()
+  const deferredDbDirty = useDeferredValue(dbDirty)
+
+  useEffect(() => database.charMeta.followAny(s => forceUpdate()), [forceUpdate, database])
+  useEffect(() => database.chars.followAny(s => forceUpdate()), [forceUpdate, database])
+
+  const locList = useMemo(() => deferredDbDirty && Array.from(new Set(
```
Comment (nguyentvan7) [inline apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/Components/AllowChar.tsx:31]: Why do we need to convert to set then to array? feels like database.chars.data shouldn't have any duplicates right?

**Review by nguyentvan7 — COMMENTED** [review]
Minor stuff

File: apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/Components/AllowChar.tsx (hunk 12 above)
Comment (frzyc) [reply apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/Components/AllowChar.tsx:31]: Because converting CharKey to LocKey will give you multiple Travelers

File: libs/localization/assets/locales/en/page_character_optimize.json (hunk 10 above)
Comment (frzyc) [reply libs/localization/assets/locales/en/page_character_optimize.json:42]: I think the way we have been exporting translations is wrong, since it would include fuzzy, which means that there will be translations that hasn't been updated. I've updated the exports in POEditor to "not fuzzy", usually I elect to just use a different key

Comment (nguyentvan7) [reply libs/localization/assets/locales/en/page_character_optimize.json:42]: I dont understand what youre saying or how that is relevant to this comment

File: apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/Components/AllowChar.tsx (hunk 11 above)
Comment (frzyc) [reply apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/Components/AllowChar.tsx:62]: should be pretty self-explanatory

File: apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/Components/AllowChar.tsx [hunk 13]
```diff
@@ -59,7 +59,7 @@ export default function AllowChar({ disabled = false, numArtsEquippedUsed }: { d
     <ModalWrapper open={show} onClose={onClose} containerProps={{ maxWidth: "xl" }}><CardDark>
       <CardContent>
         <Box display="flex" gap={1} >
-          <Typography variant="h6" flexGrow={1}>{t`excludeChar.modal.title_sel`}</Typography>
+          <Typography variant="h6" flexGrow={1}>{t`excludeChar.modal.title`}</Typography>
```
Comment (nguyentvan7) [inline apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/Components/AllowChar.tsx:62]: Oops sorry I meant this
```suggestion
          <Typography variant="h6" flexGrow={1}>{t`excludeChar.title`}</Typography>
```

**Review by nguyentvan7 — CHANGES_REQUESTED** [review]
Strings are fun

**Review by nguyentvan7 — APPROVED** [review]
