### PR TITLE
Fix resonance tooltip, adjust conditional tooltip

### LINKED ISSUE #233: Geo Infusion has empty popup
image

### PR DESCRIPTION
**Pull request by nguyentvan7**
Didn't mean to publish this branch on the main repo, woops
Fix #233 - Move tooltip to the resonance card itself, so it is always visible
chrome_1kseLE9Q18

I also standardized the tooltip for conditionals to appear above the icon

### CODE REVIEW

File: src/Types/sheet.ts [hunk 1]
```diff
@@ -10,7 +10,6 @@ export interface DocumentSection {
     icon?: Displayable | ((data: UIData) => Displayable);
     action?: Displayable;
   }
-  fieldsDescription?: Displayable | ((data: UIData) => Displayable);
```
Comment (frzyc) [inline src/Types/sheet.ts:13]: Didn't you add this to add descriptions to the headers of fields? why remove it now?
