### PR TITLE
Minor UI fixes

### LINKED ISSUE #485: Upgrading an equipped artifact via a pasted screenshot unequips the artifact
Steps to recreate:

Have a +16 artifact equipped to a character.
Take a in-game screenshot of the +20 version of the artifact and paste it into the artifacts page.
Select "Upgrade Artifact".
The Artifact will then be unequipped from the character.

This only happens if you paste/upload the image - if you manually create an upgraded version of the artifact it won't be unequipped.

### LINKED ISSUE #718: RV Filter behavior is inconsistent with other filters
image
If I were to click the "3 star" filter for artifacts here, then 3-star would be the only one selected. Then I could click "4-star" if I wanted both 3 and 4 stars to appear.

However, if I click Elemental Mastery for the RV filter, then everything bug Elemental Mastery will be selected

I also wonder if this should turn into an autocomplete, similar to substat filter?

### LINKED ISSUE #914: Artifact editor "unknown set name" remains in selection box title
image
image

### LINKED ISSUE #917: Tally system causes buttons to be out of view on mobile
imageimage

### PR DESCRIPTION
**Pull request by frzyc**
Resolve #917
Resolve #914
Resolve #485 
Resolve #718

### CODE REVIEW

**Comment by nguyentvan7** [comment]
image
Still crunches on the character page

**Review by nguyentvan7 — CHANGES_REQUESTED** [review]
See screenshot from earlier

**Comment by frzyc** [comment]
@nguyentvan7 
huh
can't replicate

**Comment by frzyc** [comment]
@nguyentvan7 
huh

File: apps/frontend/src/app/PageArtifact/ArtifactEditor.tsx [hunk 1]
```diff
@@ -254,12 +254,11 @@ export default function ArtifactEditor({ artifactIdToEdit = "", cancelEdit, allo
               {/* Artifact Set */}
               <ArtifactSetAutocomplete
                 disabled={disableSet}
-                disableClearable
                 size="small"
                 artSetKey={artifact?.setKey ?? ""}
                 setArtSetKey={updateSetKey}
                 sx={{ flexGrow: 1 }}
-                label={t("editor.unknownSetName")}
+                label={artifact?.setKey ? "" : t("editor.unknownSetName")}
```
Comment (nguyentvan7) [inline apps/frontend/src/app/PageArtifact/ArtifactEditor.tsx:261]: Think the proper way to fix this is to expose "placeholder" prop in GeneralAutocomplete that gets used in renderInput. So label should always be "Artifact Set Name" and placeholder can be "Unknown Artifact Set". But I am also ok with this fix too

Comment (frzyc) [reply apps/frontend/src/app/PageArtifact/ArtifactEditor.tsx:261]: this component doesnt really show a "placeholder", since the title occupies the space when its empty...

**Review by nguyentvan7 — APPROVED** [review]
