### PR TITLE
Fix translation of tabTheorycraft.maxTotalRolls

### LINKED ISSUE #1460: TC max roll explanation is incorrectly translated
image

### PR DESCRIPTION
**Pull request by eeeqeee**
## Issue or discord link

- Fixes #1460

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [ ] I have commented my code, in hard-to understand areas.
- [ ] I have made corresponding changes to README or wiki.
- [ ] For front-end changes, I have updated the corresponding English translations.
- [ ] Ran `yarn run mini-ci` locally to validate format + lint.
- [ ] If there were format issues, I ran `nx format write` to resolve them automatically.
- [ ] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

### CODE REVIEW

File: apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabTheorycraft/ArtifactSubCard/index.tsx [hunk 1]
```diff
@@ -87,7 +87,10 @@ export function ArtifactSubCard({
           <BootstrapTooltip
             title={
               <Typography>
-                {t('tabTheorycraft.maxTotalRolls', { value: maxTotalRolls })}
+                <Trans t={t} i18nKey={'tabTheorycraft.maxTotalRolls'}>
+                  {'The current build can only have a maximum of '}
+                  <strong>{{ value: maxTotalRolls } as any}</strong> rolls.
```
Comment (nguyentvan7) [inline apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabTheorycraft/ArtifactSubCard/index.tsx:92]: nit. we dont really need to change this now, but if we ever disallow explicit any.
```suggestion
                  <strong>{{ value: maxTotalRolls } as TransObject}</strong> rolls.
```

**Review by nguyentvan7 — APPROVED** [review]

**Review by nguyentvan7 — APPROVED** [review]
