### PR TITLE
fix baizhu burst node strings

### LINKED ISSUE #1177: Incorrect value of Baizhu's elemental burst
Baizhu's Spiritvein DMG is actually Seamless Shield Healing, and Pulsing Clarity Duration is actually Spiritvein DMG. The real Pulsing Clarity Duration is missing.
图片
图片

### PR DESCRIPTION
**Pull request by PolomoPT**
* Resolve #1177

### CODE REVIEW

File: apps/frontend/src/app/Data/Characters/Baizhu/index.tsx [hunk 1]
```diff
@@ -361,24 +361,18 @@ const sheet: ICharacterSheet = {
             unit: 's',
             fixed: 1,
           },
-          {
-            text: ct.chg('burst.skillParams.2'),
-            value: dm.burst.shieldInterval,
```
Comment (nguyentvan7) [inline apps/frontend/src/app/Data/Characters/Baizhu/index.tsx:366]: Shouldn't we still display shield interval?

Comment (PolomoPT) [reply apps/frontend/src/app/Data/Characters/Baizhu/index.tsx:366]: image

**Review by nguyentvan7 — APPROVED** [review]
