### PR TITLE
Refactor and fix header tally

### LINKED ISSUE #2252: Header item counts don't update when switching the current database
https://github.com/frzyc/genshin-optimizer/assets/81253282/cdd0cbca-9e1b-4706-a4c5-3dfc48f894ff

### PR DESCRIPTION
**Pull request by frzyc**
## Describe your changes

Add a utility function for counting the tallies in database, fix SRO header tally issue

## Issue or discord link

- Resolves #2252

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [ ] I have commented my code in hard-to understand areas.
- [ ] I have made corresponding changes to README or wiki.
- [ ] For front-end changes, I have updated the corresponding English translations.
- [ ] I have run `yarn run mini-ci` locally to validate format and lint.
- [ ] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

### CODE REVIEW

**Review by nguyentvan7 — APPROVED** [review]

File: libs/common/database-ui/src/hooks/useDatabaseTally.tsx [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+
+export function useDatabaseTally(
+  dataManager: DataManagerBase<any, any, any, any, any>
+) {
+  const [total, setTotal] = useState(dataManager.keys.length)
+  useEffect(() => {
+    setTotal(dataManager.keys.length)
+    return dataManager.followAny(
+      (_k, r) =>
+        ['new', 'remove'].includes(r) && setTotal(dataManager.keys.length)
```
Comment (nguyentvan7) [inline libs/common/database-ui/src/hooks/useDatabaseTally.tsx:12]: Why do we have to run the set total on cleanup?

Comment (frzyc) [reply libs/common/database-ui/src/hooks/useDatabaseTally.tsx:12]: `followAny` return a "unfollow", so basically every time you change datamanager, it would "register"(via followAny), and when the datamanager changes (goes out of scope), it would run the "unfollow", this makes it so that this component is only registered to listen to a singular datamanager, and new datamangers are automatically unfollowed(old datamanager) and followed(new datamanager).

For more, see "return a cleanup function" part of doc https://react.dev/reference/react/useEffect#useeffect

Comment (nguyentvan7) [reply libs/common/database-ui/src/hooks/useDatabaseTally.tsx:12]: Oh I misread the indentation on mobile, I thought we were calling setTotal in the cleanup woops
