### PR TITLE
Fix misc. sheet issues

### LINKED ISSUE #1055: Yoimiya C6 not calculated properly
naganohara meteor swarm cannot proc twice on n1/n4, rather the total multiplier from those shots are taken and then multiplied by 60%. 

with t10 normal and 13 skill it would be 
63.6% * 2 * 170.6% * 60% in 1 shot rather than 63.6% * 170.6% * 60% in 2 separate shots. the same is true for n4 except the normal attack multiplier is higher

### LINKED ISSUE #1057: Split Shenhe asc buff into two conditionals

### PR DESCRIPTION
**Pull request by nguyentvan7**
* Resolve #1055
* Resolve #1057

### CODE REVIEW

File: apps/frontend/src/app/Data/Characters/Yoimiya/index.tsx [hunk 1]
```diff
@@ -102,12 +102,17 @@ const normalEntries = dm.normal.hitArr.map((arr, i) => [
...
 
-// This might just need to be a single dmgNode of her kindling arrow, with proper scaling applied.
 const kindlingEntries = dm.normal.hitArr.map((arr, i) => [i, greaterEq(input.constellation, 6,
   equal(condSkill, "skill",
     customDmgNode(
       prod(
-        subscript(input.total.autoIndex, arr, { unit: "%" }),
+        subscript(
+          input.total.autoIndex,
+          i === 0 || i === 3
```
Comment (frzyc) [inline apps/frontend/src/app/Data/Characters/Yoimiya/index.tsx:111]: (nit) can you extract this out in a separate line `cont skillHitArr = ...` with comment

**Review by frzyc — APPROVED** [review]
